I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 107, in script
    show ace with moveleft
Exception: Parameter 'new_widget' is not known by ATL Transform.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 107, in script
    show ace with moveleft
  File "renpy/ast.py", line 1443, in execute
    renpy.exports.with_statement(trans, paired)
  File "renpy/exports.py", line 1682, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "renpy/display/core.py", line 2752, in do_with
    clear=clear)
  File "renpy/display/core.py", line 3315, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, **kwargs)
  File "renpy/display/core.py", line 3674, in interact_core
    new_widget=layers_root)
  File "renpy/atl.py", line 462, in __call__
    raise Exception('Parameter %r is not known by ATL Transform.' % k)
Exception: Parameter 'new_widget' is not known by ATL Transform.

Windows-10-10.0.19041
Ren'Py 7.4.10.2178
Arknights CC 1.0
Tue Nov  2 22:35:18 2021
