I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 90, in script
    show ruinedTent behind ace with Dissolve(2)
IOError: Couldn't find file 'forest.mp3'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 90, in script
    show ruinedTent behind ace with Dissolve(2)
  File "renpy/ast.py", line 1443, in execute
    renpy.exports.with_statement(trans, paired)
  File "renpy/exports.py", line 1682, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "renpy/display/core.py", line 2752, in do_with
    clear=clear)
  File "renpy/display/core.py", line 3315, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, **kwargs)
  File "renpy/display/core.py", line 4020, in interact_core
    renpy.audio.audio.periodic()
  File "renpy/audio/audio.py", line 1162, in periodic
    raise_(exc[0], exc[1], exc[2])
  File "renpy/audio/audio.py", line 1140, in periodic_thread_main
    periodic_pass()
  File "renpy/audio/audio.py", line 1082, in periodic_pass
    c.periodic()
  File "renpy/audio/audio.py", line 518, in periodic
    topf = load(filename)
  File "renpy/audio/audio.py", line 69, in load
    rv = renpy.loader.load(fn)
  File "renpy/loader.py", line 798, in load
    raise IOError("Couldn't find file '%s'." % name)
IOError: Couldn't find file 'forest.mp3'.

Windows-10-10.0.19041
Ren'Py 7.4.10.2178
Arknights CC 1.0
Tue Nov  2 23:00:05 2021
